import assert from 'node:assert/strict';
import {readFile,readdir,stat} from 'node:fs/promises';
import {parseHTML} from 'linkedom';
import {renderRoom} from '../dist/village/rooms.js';
import {createPlayer,advance,berries,touchedBerries,GROUND,WIDTH,platforms} from '../public/village/physics.js';
const files=(await readdir('dist',{recursive:true})).filter(p=>p.endsWith('.html'));
for(const file of files){const {document}=parseHTML(await readFile(`dist/${file}`,'utf8'));assert(document.querySelector('#world'));assert(!document.querySelector('header'));assert(!document.querySelector('footer'));const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);assert.equal(ids.length,new Set(ids).size);for(const el of document.querySelectorAll('[src],[href]')){const path=el.getAttribute('src')||el.getAttribute('href');if(path.startsWith('/'))assert((await stat(`dist${path}${path.endsWith('/')?'index.html':''}`)).isFile());}}
for(const lang of ['fr','en']){for(const route of ['about','team','game','robot','photos','journal','media','credits']){const {document}=parseHTML(renderRoom(route,lang,{page:0,tab:0}));assert.equal(document.querySelectorAll('h1').length,1,route);for(const el of document.querySelectorAll('[aria-controls]'))assert(document.getElementById(el.getAttribute('aria-controls')));}const members=new Set();for(let page=0;page<6;page++){const {document}=parseHTML(renderRoom('team',lang,{page,tab:0}));for(const name of document.querySelectorAll('.member h2'))members.add(name.textContent);}assert.equal(members.size,22);}
const player=createPlayer();let collected=[];
for(const b of berries){let steps=0;while(!collected.includes(b.id)&&steps++<1500){const dx=b.x-player.x;advance(player,{left:dx<-3,right:dx>3,jump:player.grounded&&Math.abs(dx)<110},1/120);collected.push(...touchedBerries(player,collected));}assert(collected.includes(b.id),`Berry ${b.id} must be reachable`);}
assert.equal(collected.length,12);assert.equal(touchedBerries(player,collected).length,0);
const falling=createPlayer(platforms[0].x+50);falling.y=platforms[0].y-20;falling.grounded=false;for(let i=0;i<100;i++)advance(falling,{},1/120);assert.equal(falling.y,platforms[0].y);const jumping=createPlayer();advance(jumping,{jump:true},1/60);const velocity=jumping.vy;advance(jumping,{jump:true},1/60);assert(jumping.vy>velocity,'No double jump');const edge=createPlayer(WIDTH-36);for(let i=0;i<120;i++)advance(edge,{right:true},1/120);assert(edge.x<=WIDTH-35);assert.equal(edge.y,GROUND);
console.log(`Passed: ${files.length} full-screen entry points, 8 integrated sections in both languages, all 22 team members, all 12 reachable berries, platforms, jump limits and world boundaries.`);
const normal=createPlayer(),fast=createPlayer();for(let i=0;i<240;i++){advance(normal,{right:true},1/120);advance(fast,{right:true,fast:true},1/120);}assert(fast.x-400>(normal.x-400)*1.8,'Run control must increase speed');
const {walkPose}=await import('../public/village/physics.js');assert(walkPose(20,true).front.x<walkPose(5,true).front.x,'Planted foot travels backward while body moves forward');assert(walkPose(57,true).front.y<-5,'Swing foot lifts off the ground');
const runner=createPlayer();let picked=[];for(const b of berries){let steps=0;while(!picked.includes(b.id)&&steps++<1800){const dx=b.x-runner.x;advance(runner,{left:dx<-3,right:dx>3,fast:true,jump:runner.grounded&&Math.abs(dx)<205},1/120);picked.push(...touchedBerries(runner,picked));}assert(picked.includes(b.id),`Berry ${b.id} must be reachable while running`);}console.log('Passed: double-speed movement, directional walk cycle, and all berries reachable while running.');
