export const members = Array.from({ length: 22 }, (_, i) => ({
  id: i + 1,
  name: null,
  photo: null,
  contribution: { fr: null, en: null },
}));
export const routes = [
  "",
  "village",
  "about",
  "game",
  "team",
  "robot",
  "photos",
  "journal",
  "media",
  "credits",
];
export const content = {
  fr: {
    school: "Collège Sainte-Anne de Lachine",
    subject: "Robotique",
    title: "Le village des Schtroumpfs",
    labels: [
      "Entrée",
      "Le village",
      "À propos",
      "Le jeu",
      "L’équipe",
      "Le robot",
      "Les photos",
      "Le carnet",
      "Vidéo et tutoriel",
      "Crédits",
    ],
    locale: "EN",
    localeLabel: "Switch to English",
    skip: "Aller au contenu",
    menu: "La carte",
    close: "Fermer",
    back: "Au village",
    welcome: "Psst…",
    found: "Vous avez trouvé\nnotre village",
    intro: "",
    enter: "Toc, toc !",
    opening: "Entrez !",
    entryNote: "Le village de l’équipe de robotique de Sainte-Anne.",
    villageNote: "Choisissez une maison.",
    signs: [
      "La maison commune",
      "Le terrain de jeu",
      "L’album du village",
      "L’atelier",
      "La chambre noire",
      "Le carnet de bord",
    ],
    artAlt:
      "Croquis d’un village de six maisons champignons reliées par des sentiers dans une clairière.",
    stamp: "SA",
    aboutHeading: "Pourquoi des Schtroumpfs ?",
    aboutText:
      "Notre site reprend le village et les personnages des Schtroumpfs.",
    schoolHeading: "Notre école",
    schoolText: "Collège Sainte-Anne de Lachine",
    schoolNote: "L’équipe de robotique · 22 membres à présenter.",
    crcHeading: "La compétition CRC",
    crcText:
      "Robotique CRC réunit la construction d’un robot, la programmation et des projets de communication en français et en anglais.",
    crcLink: "Le site de Robotique CRC ↗",
    pending: "À venir",
    member: "Membre",
    name: "Nom à ajouter",
    photo: "Photo à ajouter",
    contribution: "Contribution à ajouter",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",
    of: "sur",
    teamNote: "Les enseignants et les mentors seront ajoutés à la liste.",
    gameTitle: "Règles de la compétition",
    gameText: "À venir.",
    gameList: [
      "Objectif du jeu",
      "Terrain et pièces",
      "Pointage",
      "Déroulement d’une manche",
    ],
    robotTabs: ["Conception", "Plans et prototypes", "Version finale"],
    robotNotes: [
      "Choix des mécanismes, matériaux et assemblage.",
      "Dessins, essais et modifications.",
      "Le robot tel qu’il sera présenté à la compétition.",
    ],
    robotPhoto: "Photo du robot à venir.",
    photoTabs: ["Les débuts", "À l’atelier", "Le robot"],
    photoNote: "Photos à venir.",
    journalTabs: [
      "Conception",
      "Construction",
      "Kiosque",
      "Programmation",
      "Vidéo",
      "Tutoriel",
      "Site Web",
    ],
    journalLabels: ["Ce qu’on a fait", "Ce qui a coincé", "Notre solution"],
    journalDate: "Date à ajouter",
    journalNote: "Aucune entrée pour le moment.",
    mediaTabs: ["Vidéo de l’équipe", "Tutoriel"],
    mediaNotes: [
      "Vidéo de l’équipe.",
      "Une technique de l’atelier, expliquée pas à pas.",
    ],
    mediaPlaceholder: "Pas encore de vidéo.",
    creditsText:
      "Les Schtroumpfs ont été créés par Peyo. Les personnages appartiennent à leurs ayants droit. Ce projet scolaire n’est pas affilié officiellement à la franchise.",
    sourceCredit:
      "Source des renseignements sur la compétition : Robotique CRC.",
    mapTitle: "Où voulez-vous aller ?",
    home: "Accueil",
    videoShortcut: "Le cinéma",
    creditShortcut: "Crédits",
  },
  en: {
    school: "Collège Sainte-Anne de Lachine",
    subject: "Robotics",
    title: "The Smurf village",
    labels: [
      "Entrance",
      "The village",
      "About",
      "The game",
      "The team",
      "The robot",
      "Photos",
      "The notebook",
      "Video & tutorial",
      "Credits",
    ],
    locale: "FR",
    localeLabel: "Passer au français",
    skip: "Skip to content",
    menu: "The map",
    close: "Close",
    back: "To the village",
    welcome: "Psst…",
    found: "You found\nour village",
    intro: "",
    enter: "Knock, knock!",
    opening: "Come in!",
    entryNote: "Sainte-Anne’s robotics team village.",
    villageNote: "Choose a house.",
    signs: [
      "The meeting house",
      "The playing field",
      "The village album",
      "The workshop",
      "The darkroom",
      "The field notes",
    ],
    artAlt:
      "Sketch of six mushroom houses connected by paths in a woodland clearing.",
    stamp: "SA",
    aboutHeading: "Why the Smurfs?",
    aboutText:
      "Our site uses the Smurf village and characters.",
    schoolHeading: "Our school",
    schoolText: "Collège Sainte-Anne de Lachine",
    schoolNote: "The robotics team · 22 members to introduce.",
    crcHeading: "The CRC competition",
    crcText:
      "CRC Robotics combines robot construction, programming, and communication projects in French and English.",
    crcLink: "Visit CRC Robotics ↗",
    pending: "Coming soon",
    member: "Member",
    name: "Add name",
    photo: "Add photo",
    contribution: "Add contribution",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    teamNote: "Teachers and mentors will also be added to the roster.",
    gameTitle: "Competition rules",
    gameText: "Coming soon.",
    gameList: [
      "Game objective",
      "Field and pieces",
      "Scoring",
      "How a match works",
    ],
    robotTabs: ["Design", "Plans & prototypes", "Final version"],
    robotNotes: [
      "Mechanism choices, materials, and assembly.",
      "Drawings, tests, and changes.",
      "The robot as it will appear at the competition.",
    ],
    robotPhoto: "Robot photo coming soon.",
    photoTabs: ["The beginning", "In the workshop", "The robot"],
    photoNote: "Photos coming soon.",
    journalTabs: [
      "Design",
      "Construction",
      "Kiosk",
      "Programming",
      "Video",
      "Tutorial",
      "Website",
    ],
    journalLabels: ["What we did", "What went wrong", "How we fixed it"],
    journalDate: "Add date",
    journalNote: "No entries yet.",
    mediaTabs: ["Team video", "Tutorial"],
    mediaNotes: [
      "Our adventure, told by the team.",
      "A workshop technique, one step at a time.",
    ],
    mediaPlaceholder: "No video yet.",
    creditsText:
      "The Smurfs were created by Peyo. The characters belong to their respective rights holders. This school project is not officially affiliated with the franchise.",
    sourceCredit: "Competition information source: CRC Robotics.",
    mapTitle: "Where are you going?",
    home: "Home",
    videoShortcut: "The cinema",
    creditShortcut: "Credits",
  },
};
